spring:
  application:
    name: msaccommodation
  datasource:
    url: jdbc:h2:mem:testdb
    username: dev
    password: 

server:
  port: 0

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://user:password@localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

