spring:
  application:
    name: ms-gateway
  
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
      - id: ms-accommodation
        uri: lb://ms-accommodation
        predicates:
        - Path=/accommodations/**
        filters:
        - StripPrefix=1
    

server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${server.address:${random.value}}
